Project Structure: {
  shape: sql_table
  "CMakeLists.txt": CMake project
  "animalabstractlistmodel.[cpp|h]": Subclass of QAbstractListModel
  "animalmodel.h": A simple model class for animals
  "printservice.h": A QML_ELEMENT class for printing all animals
  "main.cpp": Main file
  "Main.qml": Main QML file
  "qtquickcontrols2.conf": Configuration file for Qt Quick Controls
}
