version: 2
updates:
- package-ecosystem: npm
  directory: "/themes/Spark2/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
