trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

pr: none

variables:
  HUGO_VERSION: '0.55.6'

steps:
  - script: |
      wget -c https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
      tar -zxvf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
    displayName: Downloading Hugo
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
  - script: |
      python --version
      pip --version
    displayName: Installing python dependencies