trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

pr: none

variables:
  HUGO_VERSION: '0.58.0'
  HUGO_ENV: 'production'


steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
    displayName: Using Python 3.7
  - task: NodeTool@0
    inputs:
      versionSpec: 10.16.0
    displayName: Using NodeJs 10.16.0
  - script: |
      node --version
      npm --version
      python --version
      pip --version
    displayName: Checking for Installed Versions
  - script: |
      wget -c https://github.com/gohugoio/hugo/releases/download/v$(HUGO_VERSION)/hugo_extended_$(HUGO_VERSION)_Linux-64bit.tar.gz
      tar -zxvf hugo_extended_$(HUGO_VERSION)_Linux-64bit.tar.gz
      sudo mv ./hugo /usr/local/bin
      hugo version
    displayName: Installing Hugo
  - script: |
      pip install -r requirements.txt
    displayName: Installing Python Dependencies
  - script: |
      npm install -g firebase-tools
    displayName: Installing Firebase CLI Tools
  - script: hugo -v --minify --gc
    displayName: Build Hugo
    env:
      HUGO_ENV: $(HUGO_ENV)
  - script: |
      firebase --version
      firebase deploy --token "$(firebase)"
    displayName: Deploy Website to Firebase
  - script: |
      python utils.py
    displayName: Running Python Script
    env:
      ALGOLIA_KEY: $(ALGOLIA_KEY)
