trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

pr: none

variables:
  HUGO_VERSION: '0.55.6'

steps:
  - script: |
      wget -c https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
      tar -zxvf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
    displayName: Downloading Hugo
  - script: |
      sudo python3 -m pip uninstall pip && sudo apt-get install python3-pip --reinstall
      sudo -H pip3 install --upgrade pip
      sudo pip3 install -r requirements.txt
      pip3 freeze
    displayName: Installing python dependencies