name: Build Hugo site

on:
  push:
    branches: ["master"]

defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Hugo CLI
        run: |
          version=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | python -c 'import json,sys;print(json.load(sys.stdin)["tag_name"])' | cut -c 2-)
          echo "Latest version ${version}"
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${version}/hugo_extended_${version}_Linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
